language: java
git:
  depth: false
addons:
  sonarcloud:
    organization: dependency-check
    token:
      secure: DoKbTc6euo/1GBD6u2pVzOhK4v9gf8ZJacsQaSU4zbnL5uYTknTBO+x+8eNGBLtoLHx28Rk5HPrZDK4ADZch1Zzy92qxV0A8/m7zJcZQQlK2Mb1TohOtCEA7ACnf53xUAH+XpSdAfgKLLk7gl8Q2B3rOaDG5uxPciUg5jqfuWV4=
jobs:
  include:
    - name: OpenJDK 11 with SonarQube
      language: java
      jdk: openjdk11
      script:
        - mvn clean verify sonar:sonar -Dsonar.projectKey=dependency-check_dependency-check-sonar-plugin
    - name: OpenJDK 8
      language: java
      jdk: openjdk8
      script:
        - mvn clean verify
